/**
 * Documents Explorer - Internal Category Router
 *
 * Handles category switching WITHOUT changing the URL
 * All navigation happens within the same page
 *
 * @module explorer/router
 */

import type { DocumentCategory } from './types';
import { stateManager } from './state';
import { setHTML } from '../../../utils/dom-utils';

/**
 * Router class
 * Manages internal category navigation without URL changes
 */
class Router {
  private currentCategory: DocumentCategory = 'all';

  constructor() {
    // Styles are now handled by Design System (breadcrumb.css)
    this.setupListeners();
  }

  /**
   * Setup event listeners
   */
  private setupListeners(): void {
    // Handle sidebar clicks - no URL changes
    document.addEventListener('click', (e) => {
      const target = e.target as HTMLElement;
      const folderItem = target.closest('.folder-item');

      if (folderItem) {
        e.preventDefault();
        const categoryAttr = folderItem.getAttribute('data-category');
        // Only proceed if we have a valid category attribute (not null or empty string)
        if (categoryAttr !== null && categoryAttr !== '') {
          const category = categoryAttr as DocumentCategory;
          if (category !== this.currentCategory) {
            this.navigateToCategory(category);
          }
        }
      }
    });
  }

  /**
   * Navigate to a category (internal only, no URL change)
   * @param category - Document category
   */
  public navigateToCategory(category: DocumentCategory): void {
    if (this.currentCategory === category) {
      return; // Already on this category
    }

    this.currentCategory = category;
    this.handleCategoryRoute(category);
  }

  /**
   * Handle category route
   * Updates state manager with new category
   */
  private handleCategoryRoute(category: DocumentCategory): void {
    // Validate category
    const validCategories: DocumentCategory[] = [
      'all',
      'personal',
      'team',
      'department',
      'company',
      'payroll',
      'blackboard',
      'chat',
    ];

    if (!validCategories.includes(category)) {
      console.warn(`Invalid category: ${category}, defaulting to "all"`);
      category = 'all';
    }

    // Update state
    stateManager.setCategory(category);

    // Update breadcrumb
    this.updateBreadcrumb(category);

    // Update active state in sidebar
    this.updateSidebarActiveState(category);
  }

  /**
   * Update breadcrumb navigation
   * Matches BEM structure generated by breadcrumb.js for consistency
   */
  private updateBreadcrumb(category: DocumentCategory): void {
    const breadcrumbContainer = document.getElementById('breadcrumb-container');
    if (!breadcrumbContainer) return;

    const categoryLabels: Record<DocumentCategory, string> = {
      all: 'Alle Dokumente',
      personal: 'Persönliche Dokumente',
      team: 'Team Dokumente',
      department: 'Abteilung',
      company: 'Firma',
      payroll: 'Gehaltsabrechnungen',
      blackboard: 'Schwarzes Brett',
      chat: 'Chat Anhänge',
    };

    // Safe: category is typed as DocumentCategory union, always returns valid string
    // eslint-disable-next-line security/detect-object-injection
    const label = categoryLabels[category];

    const breadcrumbContent = `
      <nav class="breadcrumb" aria-label="Breadcrumb">
        <a href="/" class="breadcrumb__item">
          <i class="fas fa-home breadcrumb__icon" aria-hidden="true"></i>
          Home
        </a>
        <span class="breadcrumb__separator" aria-hidden="true">
          <i class="fas fa-chevron-right"></i>
        </span>
        <a href="/documents-explorer" class="breadcrumb__item">
          <i class="fas fa-folder breadcrumb__icon" aria-hidden="true"></i>
          Dokumente
        </a>
        <span class="breadcrumb__separator" aria-hidden="true">
          <i class="fas fa-chevron-right"></i>
        </span>
        <span class="breadcrumb__item breadcrumb__item--active" aria-current="page">
          <i class="fas fa-folder-open breadcrumb__icon" aria-hidden="true"></i>
          ${label}
        </span>
      </nav>
    `;

    // Use safe HTML setter from dom-utils
    setHTML(breadcrumbContainer, breadcrumbContent);
  }

  /**
   * Update active state in sidebar
   */
  private updateSidebarActiveState(category: DocumentCategory): void {
    // Remove active class from all folder items
    const allFolderItems = document.querySelectorAll('.folder-item');
    allFolderItems.forEach((item) => {
      item.classList.remove('bg-surface-3', 'text-primary-500');
      item.classList.add('text-content-primary');

      // Update icon color
      const icon = item.querySelector('span:first-child');
      if (icon) {
        icon.classList.remove('text-primary-500');
        icon.classList.add('text-content-secondary');
      }

      // Update text weight
      const label = item.querySelector('span.text-sm');
      if (label) {
        label.classList.remove('font-medium');
      }
    });

    // Add active class to current category
    const activeItem = document.querySelector(`[data-category="${category}"]`);
    if (activeItem) {
      activeItem.classList.remove('text-content-primary');
      activeItem.classList.add('bg-surface-3', 'text-primary-500');

      // Update icon color
      const icon = activeItem.querySelector('span:first-child');
      if (icon) {
        icon.classList.remove('text-content-secondary');
        icon.classList.add('text-primary-500');
      }

      // Update text weight
      const label = activeItem.querySelector('span.text-sm');
      if (label) {
        label.classList.add('font-medium');
      }
    }
  }

  /**
   * Initialize router
   * Sets initial category to 'all'
   */
  public init(): void {
    // Always start with "all" category
    this.currentCategory = 'all';
    this.handleCategoryRoute('all');
  }

  /**
   * Get current category
   */
  public getCurrentCategory(): DocumentCategory {
    return this.currentCategory;
  }
}

// Export singleton instance
export const router = new Router();
