-- Migration: 007-audit-trail-request-id.sql
-- Purpose: Add request_id column to audit_trail for request correlation
-- Related: ADR-009 Central Audit Logging Improvement Plan
-- Date: 2026-01-22

-- ============================================================================
-- ADD REQUEST_ID COLUMN TO PARENT TABLE
-- ============================================================================

-- Add nullable UUID column for request correlation
-- Allows grouping multiple audit entries from the same HTTP request
ALTER TABLE audit_trail ADD COLUMN IF NOT EXISTS request_id UUID;

-- Create index for efficient request correlation queries
-- NOTE: CONCURRENTLY cannot be used on partitioned tables
-- The index is automatically propagated to partitions
CREATE INDEX IF NOT EXISTS idx_audit_trail_request_id
ON audit_trail (request_id)
WHERE request_id IS NOT NULL;

-- ============================================================================
-- VERIFICATION
-- ============================================================================

-- Verify column was added
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'audit_trail'
        AND column_name = 'request_id'
    ) THEN
        RAISE NOTICE '✅ request_id column added to audit_trail';
    ELSE
        RAISE EXCEPTION '❌ Failed to add request_id column';
    END IF;
END $$;

-- ============================================================================
-- USAGE NOTES
-- ============================================================================
--
-- The request_id allows correlating multiple audit entries from the same request.
--
-- Example query - find all actions from one request:
--   SELECT * FROM audit_trail WHERE request_id = 'abc-123-uuid' ORDER BY created_at;
--
-- Example query - requests with multiple audit entries (potential issues):
--   SELECT request_id, COUNT(*) as entry_count
--   FROM audit_trail
--   WHERE request_id IS NOT NULL
--   GROUP BY request_id
--   HAVING COUNT(*) > 1
--   ORDER BY entry_count DESC;
--
-- The request_id is generated by nestjs-cls middleware (UUIDv4).
-- It can also be passed via X-Request-ID header from nginx/load balancer.
-- ============================================================================
