-- =====================================================
-- Migration: Add UUID to conversations table
-- Date: 2025-12-03
-- Author: Claude
-- Purpose: Enable URL-based routing for chat (/chat/:uuid)
-- Pattern: Same as KVP and Blackboard (UUIDv7 generated in app)
-- =====================================================

-- 1. Add uuid column (matches KVP/Blackboard pattern: CHARACTER(36))
ALTER TABLE conversations
ADD COLUMN IF NOT EXISTS uuid CHARACTER(36);

-- 2. Add uuid_created_at column (for UUIDv7 timestamp extraction)
ALTER TABLE conversations
ADD COLUMN IF NOT EXISTS uuid_created_at TIMESTAMPTZ;

-- 3. Generate UUIDs for existing rows
-- NOTE: Using gen_random_uuid() as fallback for existing data
-- New conversations will use UUIDv7 generated by the app
UPDATE conversations
SET
    uuid = gen_random_uuid()::TEXT,
    uuid_created_at = NOW()
WHERE uuid IS NULL;

-- 4. Make uuid NOT NULL after populating existing rows
ALTER TABLE conversations
ALTER COLUMN uuid SET NOT NULL;

-- 5. Create unique index on uuid for fast lookups
CREATE UNIQUE INDEX IF NOT EXISTS idx_conversations_uuid
ON conversations(uuid);

-- 6. Grant permissions to app_user
GRANT SELECT, INSERT, UPDATE, DELETE ON conversations TO app_user;

-- 7. Verify migration
DO $$
DECLARE
    uuid_column_exists BOOLEAN;
    null_uuid_count INTEGER;
BEGIN
    -- Check column exists
    SELECT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'conversations' AND column_name = 'uuid'
    ) INTO uuid_column_exists;

    IF NOT uuid_column_exists THEN
        RAISE EXCEPTION 'Migration failed: uuid column not created';
    END IF;

    -- Check no NULL UUIDs
    SELECT COUNT(*) INTO null_uuid_count
    FROM conversations WHERE uuid IS NULL;

    IF null_uuid_count > 0 THEN
        RAISE EXCEPTION 'Migration failed: % rows have NULL uuid', null_uuid_count;
    END IF;

    RAISE NOTICE 'Migration successful: uuid column added to conversations table';
END $$;
