/**
 * Migration: Add request_id to audit_trail for request correlation
 * Date: 2026-01-22 (original) / 2026-01-27 (wrapped)
 * ADR: ADR-009 Central Audit Logging
 *
 * Allows grouping multiple audit entries from the same HTTP request.
 * Generated by nestjs-cls middleware (UUIDv4) or X-Request-ID header.
 */
import type { MigrationBuilder } from 'node-pg-migrate';

export function up(pgm: MigrationBuilder): void {
  pgm.sql(`
    ALTER TABLE audit_trail ADD COLUMN IF NOT EXISTS request_id UUID;

    CREATE INDEX IF NOT EXISTS idx_audit_trail_request_id
    ON audit_trail (request_id)
    WHERE request_id IS NOT NULL;
  `);
}

export function down(pgm: MigrationBuilder): void {
  pgm.sql(`
    DROP INDEX IF EXISTS idx_audit_trail_request_id;
    ALTER TABLE audit_trail DROP COLUMN IF EXISTS request_id;
  `);
}
