/**
 * Migration: Vacation Legacy Cleanup
 * Date: 2026-02-12
 *
 * Drops the legacy `absences` table and its associated ENUM types.
 * The absences functionality is now replaced by the vacation request system
 * (vacation_requests, vacation_request_status_log, user_availability).
 *
 * Safety: A pre-check verifies the absences table is empty. If data exists,
 * the migration will RAISE NOTICE and proceed (data was already confirmed
 * empty during pre-implementation verification).
 *
 * References: FEAT_VACCATION_MASTERPLAN.md (Phase 1, Step 1.4)
 */
import type { MigrationBuilder } from 'node-pg-migrate';

export function up(pgm: MigrationBuilder): void {
  pgm.sql(`
    -- ==========================================================================
    -- Pre-check: warn if absences table has data (R3 mitigation)
    -- ==========================================================================

    DO $$
    DECLARE
        _count INTEGER;
    BEGIN
        SELECT COUNT(*) INTO _count FROM absences;
        IF _count > 0 THEN
            RAISE NOTICE 'WARNING: absences table has % row(s). Data will be lost.', _count;
        END IF;
    END $$;

    -- ==========================================================================
    -- Drop legacy absences table + ENUMs
    -- ==========================================================================

    DROP TABLE IF EXISTS absences CASCADE;
    DROP TYPE IF EXISTS absences_type CASCADE;
    DROP TYPE IF EXISTS absences_status CASCADE;
  `);
}

export function down(pgm: MigrationBuilder): void {
  pgm.sql(`
    -- Recreate legacy ENUM types
    CREATE TYPE absences_type AS ENUM ('vacation', 'sick', 'training', 'other');
    CREATE TYPE absences_status AS ENUM ('pending', 'approved', 'rejected', 'cancelled');

    -- Recreate legacy absences table
    CREATE TABLE absences (
        id          INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        tenant_id   INTEGER NOT NULL REFERENCES tenants(id) ON UPDATE RESTRICT ON DELETE CASCADE,
        user_id     INTEGER NOT NULL REFERENCES users(id) ON UPDATE RESTRICT ON DELETE CASCADE,
        type        absences_type NOT NULL,
        start_date  DATE NOT NULL,
        end_date    DATE NOT NULL,
        reason      TEXT,
        status      absences_status DEFAULT 'pending',
        approved_by INTEGER REFERENCES users(id) ON UPDATE RESTRICT ON DELETE SET NULL,
        approved_at TIMESTAMPTZ,
        created_at  TIMESTAMPTZ DEFAULT NOW()
    );

    CREATE INDEX idx_absences_tenant ON absences(tenant_id);
    CREATE INDEX idx_absences_user ON absences(user_id);
    CREATE INDEX idx_absences_dates ON absences(start_date, end_date);
    CREATE INDEX idx_absences_status ON absences(status);
    CREATE INDEX idx_absences_type ON absences(type);
    CREATE INDEX idx_absences_approved_by ON absences(approved_by);

    ALTER TABLE absences ENABLE ROW LEVEL SECURITY;
    ALTER TABLE absences FORCE ROW LEVEL SECURITY;

    CREATE POLICY tenant_isolation ON absences
        FOR ALL
        USING (
            NULLIF(current_setting('app.tenant_id', true), '') IS NULL
            OR tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::integer
        );

    GRANT SELECT, INSERT, UPDATE, DELETE ON absences TO app_user;
  `);
}
