#!/bin/bash
# =============================================================================
# Sync Customer Migrations Script
# =============================================================================
#
# Aktualisiert customer/fresh-install/ aus aktueller DB:
#   1. Schema-Dump → archive/ + customer/
#   2. Seed-Dump → customer/
#   3. pgmigrations SQL → customer/ (dynamisch generiert)
#
# VERWENDUNG: Nach jeder Migration ausführen!
#   ./scripts/sync-customer-migrations.sh
#
# =============================================================================

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Config
CONTAINER="assixx-postgres"
DB_USER="assixx_user"
DB_NAME="assixx"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Check container
if ! docker ps --format '{{.Names}}' | grep -q "^${CONTAINER}$"; then
    log_error "Container '${CONTAINER}' nicht running!"
    exit 1
fi

log_info "Synchronisiere Customer Fresh-Install..."

# Ensure directories exist
mkdir -p "${PROJECT_ROOT}/customer/fresh-install"
mkdir -p "${PROJECT_ROOT}/database/migrations/archive"

# =============================================================================
# 1. Schema dumpen → archive/ + customer/
# =============================================================================
log_info "Dumpe Schema..."
docker exec ${CONTAINER} pg_dump -U ${DB_USER} -d ${DB_NAME} \
    --schema-only --no-owner --no-privileges --quote-all-identifiers \
    -f /tmp/schema.sql

docker cp ${CONTAINER}:/tmp/schema.sql \
    "${PROJECT_ROOT}/database/migrations/archive/001_baseline_complete_schema.sql"

cp "${PROJECT_ROOT}/database/migrations/archive/001_baseline_complete_schema.sql" \
   "${PROJECT_ROOT}/customer/fresh-install/001_schema.sql"

log_info "Schema synchronisiert."

# =============================================================================
# 2. Seed-Data dumpen → customer/
# =============================================================================
log_info "Dumpe Seed-Data..."
docker exec ${CONTAINER} pg_dump -U ${DB_USER} -d ${DB_NAME} \
    --data-only --inserts --no-owner --no-privileges \
    -t plans -t features -t plan_features -t kvp_categories -t asset_categories \
    -f /tmp/seed.sql

docker cp ${CONTAINER}:/tmp/seed.sql \
    "${PROJECT_ROOT}/customer/fresh-install/002_seed_data.sql"

log_info "Seed-Data synchronisiert."

# =============================================================================
# 3. pgmigrations SQL generieren → customer/
# =============================================================================
log_info "Generiere 005_pgmigrations.sql..."

PGMIGRATIONS_FILE="${PROJECT_ROOT}/customer/fresh-install/005_pgmigrations.sql"
MIGRATION_COUNT=0

cat > "${PGMIGRATIONS_FILE}" << 'HEADER'
-- =============================================================================
-- Migration Tracking - node-pg-migrate compatibility
-- =============================================================================
-- AUTO-GENERATED by sync-customer-migrations.sh - DO NOT EDIT MANUALLY!
--
-- Registers all known migrations as "already applied" so that
-- node-pg-migrate does not attempt to re-run them after a fresh install.
-- =============================================================================

-- Create pgmigrations table (node-pg-migrate default tracking table)
CREATE TABLE IF NOT EXISTS pgmigrations (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    run_on TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Register all migrations as applied
HEADER

for ts_file in $(find "${PROJECT_ROOT}/database/migrations" -maxdepth 1 -name '2*.ts' -type f | sort); do
    name=$(basename "${ts_file}" .ts)
    echo "INSERT INTO pgmigrations (name, run_on) VALUES ('${name}', NOW()) ON CONFLICT DO NOTHING;" >> "${PGMIGRATIONS_FILE}"
    MIGRATION_COUNT=$((MIGRATION_COUNT + 1))
done

# Add unique constraint if not exists (for ON CONFLICT DO NOTHING)
cat >> "${PGMIGRATIONS_FILE}" << 'FOOTER'

-- Add unique constraint on name (idempotent)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'pgmigrations_name_unique'
    ) THEN
        ALTER TABLE pgmigrations ADD CONSTRAINT pgmigrations_name_unique UNIQUE (name);
    END IF;
END $$;

-- Sync sequence
SELECT setval('pgmigrations_id_seq', GREATEST((SELECT MAX(id) FROM pgmigrations), 1), true);

-- Verify
DO $$
DECLARE
    migration_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO migration_count FROM pgmigrations;
    RAISE NOTICE 'pgmigrations: % migrations registered', migration_count;
END $$;
FOOTER

log_info "005_pgmigrations.sql generiert: ${MIGRATION_COUNT} Migrationen."

# =============================================================================
# 4. Verifizieren
# =============================================================================
log_info "Verifiziere..."

DIFF_SCHEMA=$(diff "${PROJECT_ROOT}/database/migrations/archive/001_baseline_complete_schema.sql" \
                   "${PROJECT_ROOT}/customer/fresh-install/001_schema.sql" > /dev/null 2>&1 && echo "OK" || echo "DIFF")

echo ""
echo "========================================================"
echo "  SYNC COMPLETE"
echo "========================================================"
echo "  001_schema.sql:        archive <-> customer  ${DIFF_SCHEMA}"
echo "  002_seed_data.sql:     dumped to customer     OK"
echo "  005_pgmigrations.sql:  ${MIGRATION_COUNT} migrations  OK"
echo "========================================================"

if [ "${DIFF_SCHEMA}" = "OK" ]; then
    log_info "Alle Dateien synchronisiert!"
else
    log_error "Schema-Synchronisation fehlgeschlagen!"
    exit 1
fi

log_warn "Hinweis: Falls Seed-Daten geändert wurden, auch database/seeds/001_global-seed-data.sql manuell aktualisieren (ON CONFLICT DO NOTHING Format)."
